export const GROUP_ADD_REQUEST = "GROUP_ADD_REQUEST";
export const GROUP_DELETE_REQUEST = "GROUP_DELETE_REQUEST";
export const CONTACT_ADD_REQUEST = "CONTACT_ADD_REQUEST";
export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST";
export const GROUP_SEARCH_REQUEST = "GROUP_SEARCH_REQUEST";
export const CONTACT_SEARCH_REQUEST = "CONTACT_SEARCH_REQUEST";
